SELECT ?PumpIdentifier ?PumpNormalFlowRateMeterCubedPerHour
WHERE {
    ?possibleindividual rdf:type dm:PossibleIndividual .
    ?classificationofindividual tpl:hasClassifier <http://data.posccaesar.org/rdl/RDS416834> .
    ?classificationofindividual tpl:hasClassified ?possibleindividual .
    ?classificationofindividual rdf:type tpl:ClassificationOfIndividual .
    ?individualhasindirectpropertywithvalue tpl:hasScale <http://data.posccaesar.org/rdl/RDS1321064> .
    ?individualhasindirectpropertywithvalue tpl:hasPossessor ?possibleindividual .
    ?individualhasindirectpropertywithvalue tpl:hasIndirectPropertyType <http://data.posccaesar.org/rdl/RDS7354451> .
    ?individualhasindirectpropertywithvalue rdf:type tpl:IndividualHasIndirectPropertyWithValue .
    ?classifiedidentificationofindividual tpl:hasIdentified ?possibleindividual .
    ?classifiedidentificationofindividual tpl:hasIdentificationType <http://data.posccaesar.org/rdl/RDS2100944981> .
    ?classifiedidentificationofindividual rdf:type tpl:ClassifiedIdentificationOfIndividual .
    ?individualhasindirectpropertywithvalue tpl:valPropertyValue ?PumpNormalFlowRateMeterCubedPerHour .
    ?classifiedidentificationofindividual tpl:valIdentifier ?PumpIdentifier .
}